export const AUTH_LOGIN_SUCCES = 'AUTH_LOGIN_SUCCES';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADS_LOADED_REQUEST = 'ADS_LOADED_REQUEST';
export const ADS_LOADED_SUCCES = 'ADS_LOADED_SUCCES';
export const ADS_LOADED_FAILURE = 'ADS_LOADED_FAILURE';

export const AD_LOADED_REQUEST = 'AD_LOADED_REQUEST';
export const AD_LOADED_SUCCES = 'AD_LOADED_SUCCES';
export const AD_LOADED_FAILURE = 'AD_LOADED_FAILURE';

export const CREATED_AD_REQUEST = 'CREATED_AD_REQUEST';
export const CREATED_AD_SUCCES = 'CREATED_AD_SUCCES';
export const CREATED_AD_FAILURE = 'CREATED_AD_FAILURE';

export const DELETED_AD_REQUEST = 'DELETED_AD_REQUEST';
export const DELETED_AD_SUCCES = 'DELETED_AD_SUCCES';
export const DELETED_AD_FAILURE = 'DELETED_AD_FAILURE';

export const TAGS_LOADED_REQUEST = 'TAGS_LOADED_REQUEST';
export const TAGS_LOADED_SUCCES = 'TAGS_LOADED_SUCCES';
export const TAGS_LOADED_FAILURE = 'TAGS_LOADED_FAILURE';

export const UI_RESET_ERROR = 'UI_RESET_ERROR';